/*
 * This source file was generated by the Gradle 'init' task
 */
package _ordenacao_produtos;

import java.io.IOException;

import _ordenacao_produtos.utils.VendasProdutos;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {
        System.out.println(new App().getGreeting());

        VendasProdutos.main(args);
    }
}
