/*
 * This source file was generated by the Gradle 'init' task
 */
package _fila_atendimento2;

import _fila_atendimento2.utils.FilaAtendimento;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        FilaAtendimento.main(args);
    }
}